version: "2.4"
services:
  chain:
    container_name: chain
    restart: unless-stopped
    build:
      context: ..
      dockerfile: Dockerfile
    volumes:
      - ../src:/service/src
    ports:
      - "33080:18000"
    environment:
      - PYTHONDONTWRITEBYTECODE=1
    depends_on:
      - ollama_local
    command: ["python", "-m", "src.chain"]

  ollama_local:
    volumes:
      - ../.ollama:/root/.ollama
      - ../bin/ollama_entrypoint.sh:/root/ollama_entrypoint.sh
    image: ollama/ollama:latest
    runtime: nvidia
    container_name: ollama_local
    pull_policy: always
    # tty: true
    restart: unless-stopped
    ports:
      - 17434:11434
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - NVIDIA_VISIBLE_DEVICES=5
    entrypoint: [ "/root/ollama_entrypoint.sh" ]
